# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import learnslug.models


class Migration(migrations.Migration):

    dependencies = [
        ('learnslug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(slugify=learnslug.models.custom_slugify, unique_with=('pub_date__month',)),
        ),
    ]
